package com.biprom.amcal.amcalpompen.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Upload;
import com.vaadin.ui.Grid;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.InlineDateTimeField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DetailTicketDesign extends VerticalLayout {
    protected TextField tfArtikelNummer;
    protected TextField tfJaarInstallatie;
    protected TextField tfWeekInstallatie;
    protected InlineDateTimeField datefAanmaakDatum;
    protected TextArea taOmschrijvingInstallatie;
    protected Upload uplFotoInstallatie;
    protected TextField tfArtikelNummerPomp;
    protected TextField tfJaarPomp;
    protected TextField tfWeekPomp;
    protected TextArea taOmschrijvingPomp;
    protected Upload ulFotoPomp;
    protected Grid<com.biprom.amcal.amcalpompen.Entities.Product> tbBenodigdMateriaal;
    protected TextArea taVaststellingTechnieker;
    protected TextArea taInterneOpmerkingen;
    protected Grid<com.biprom.amcal.amcalpompen.Entities.WerkUren> tbWerkuren;
    protected TextField tfRamingUren;
    protected CheckBox checkbOpdrachtAfgewerkt;
    protected CheckBox checkbDeeltelijksFacturatie;
    protected CheckBox checkbVerderInTePlannen;

    public DetailTicketDesign() {
        Design.read(this);
    }
}
