package com.biprom.amcal.amcalpompen.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TextArea;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class KlantenGegevevensDetailDesign extends VerticalLayout {
    protected TextField tfLeverStraat1;
    protected TextField tfLeverNummer1;
    protected TextField tfLeverBus1;
    protected TextField tfLeverPostcode1;
    protected TextField tfLeverStad1;
    protected TextField tfLeverLand1;
    protected TextArea tfLeverCommentaar1;
    protected TextField tfLeverStraat2;
    protected TextField tfLeverNummer2;
    protected TextField tfLeverBus2;
    protected TextField tfLeverPostcode2;
    protected TextField tfLeverStad2;
    protected TextField tfLeverLand2;
    protected TextArea tfLeverCommentaar2;
    protected TextField tfLeverStraat3;
    protected TextField tfLeverNummer3;
    protected TextField tfLeverBus3;
    protected TextField tfLeverPostcode3;
    protected TextField tfLeverStad3;
    protected TextField tfLeverLand3;
    protected TextArea tfLeverCommentaar3;
    protected TextField tfLeverStraat4;
    protected TextField tfLeverNummer4;
    protected TextField tfLeverBus4;
    protected TextField tfLeverPostcode4;
    protected TextField tfLeverStad4;
    protected TextField tfLeverLand4;
    protected TextArea tfLeverCommentaar4;

    public KlantenGegevevensDetailDesign() {
        Design.read(this);
    }
}
