package com.biprom.amcal.amcalpompen.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class KlantenGegevensContactpersonenDesign extends VerticalLayout {
    protected TextField tfContactNaam1;
    protected TextField tfContactVoornaam1;
    protected TextField tfContactTel1;
    protected TextField tfContactGSM1;
    protected TextField tfContactEmail1;
    protected TextField tfContactNaam2;
    protected TextField tfContactVoornaam2;
    protected TextField tfContactTel2;
    protected TextField tfContactGSM2;
    protected TextField tfContactEmail2;
    protected TextField tfContactNaam3;
    protected TextField tfContactVoornaam3;
    protected TextField tfContactTel3;
    protected TextField tfContactGSM3;
    protected TextField tfContactEmail3;
    protected TextField tfContactNaam4;
    protected TextField tfContactVoornaam4;
    protected TextField tfContactTel4;
    protected TextField tfContactGSM4;
    protected TextField tfContactEmail4;
    protected TextField tfContactNaam5;
    protected TextField tfContactVoornaam5;
    protected TextField tfContactTel5;
    protected TextField tfContactGSM5;
    protected TextField tfContactEmail5;
    protected TextField tfContactNaam6;
    protected TextField tfContactVoornaam6;
    protected TextField tfContactTel6;
    protected TextField tfContactGSM6;
    protected TextField tfContactEmail6;
    protected TextField tfContactNaam7;
    protected TextField tfContactVoornaam7;
    protected TextField tfContactTel7;
    protected TextField tfContactGSM7;
    protected TextField tfContactEmail7;
    protected TextField tfContactNaam8;
    protected TextField tfContactVoornaam8;
    protected TextField tfContactTel8;
    protected TextField tfContactGSM8;
    protected TextField tfContactEmail8;

    public KlantenGegevensContactpersonenDesign() {
        Design.read(this);
    }
}
