package com.biprom.amcal.amcalpompen.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class KlantenGegevensDesign extends VerticalLayout {
    protected TextField tfBedrijfsNaam;
    protected TextField tfAfdeling;
    protected TextField tfFacStraat;
    protected TextField tfFacNummer;
    protected TextField tfFacBus;
    protected TextField tfFacPostCode;
    protected TextField tfFacStad;
    protected TextField tfFacLand;
    protected TextArea tfFacCommentaar;
    protected Button bKlantOpslaan;

    public KlantenGegevensDesign() {
        Design.read(this);
    }
}
