package com.biprom.amcal.amcalpompen.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.ComboBox;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class nieuwTicketDesign extends VerticalLayout {
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Klanten> cbOpdrachtgever;
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Personen> cbContactPersoon;
    protected ComboBox<String> cbEindklant;

    public nieuwTicketDesign() {
        Design.read(this);
    }
}
