package com.biprom.amcal.amcalpompen.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.TextField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.InlineDateTimeField;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class nieuwTicketDesign extends Panel {
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Klanten> cbOpdrachtgever;
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Personen> cbContactPersoon;
    protected TextField tfGsmNummer;
    protected TextField tfReferentieOpdrachtgever;
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Adres> cbFacturatieAdres;
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Klanten> cbEindklant;
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Personen> cbEindklantContactPersoon;
    protected TextField tfEindklantGsmNummer;
    protected TextField tfEindklantReferentie;
    protected ComboBox<com.biprom.amcal.amcalpompen.Entities.Adres> cbEindklantLeverAdres;
    protected ComboBox<Integer> cbPrioriteitTicket;
    protected CheckBox checkbInterventie;
    protected CheckBox checkbBestek;
    protected CheckBox checkbBestekGoedgekeurd;
    protected CheckBox checkbUitvoering;
    protected CheckBox checkbofferte;
    protected CheckBox checkbOfferteGoedgekeurd;
    protected TextArea tfProbleemOmschrijving;
    protected TextArea tfInterneOmperkingen;
    protected InlineDateTimeField dpDatumTicket;
    protected TextField tfTicketnummer;
    protected Button bSlaTicketOp;

    public nieuwTicketDesign() {
        Design.read(this);
    }
}
