package com.biprom.amcal.amcalpompen.Design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.declarative.Design;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Button;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class StockTellingDesign extends Panel {
    protected TextField tfArtikelCode;
    protected TextField tfStockAantal;
    protected TextField tfCommentaarToevoeging;
    protected TextField tfBulkNummer;
    protected TextField tfAantalInBulk;
    protected CheckBox checkbPompOnderdeel;
    protected CheckBox checkbMotorLager;
    protected CheckBox checkbCompletePomp;
    protected CheckBox checkbCompleteMotor;
    protected CheckBox checkbElekrischMateriaal;
    protected CheckBox checkbMechanischMateriaal;
    protected CheckBox checkbCRN1;
    protected CheckBox checkbCRN3;
    protected CheckBox checkbCRN5;
    protected CheckBox checkbCRN10;
    protected CheckBox checkbCRN15;
    protected CheckBox checkbCRN20;
    protected CheckBox checkbCRN32;
    protected CheckBox checkbCRN45;
    protected CheckBox checkbCRN90;
    protected CheckBox checkbCRN120;
    protected CheckBox checkbCRN150;
    protected CheckBox checkbCRN2;
    protected CheckBox checkbCRN4;
    protected CheckBox checkbCRN8;
    protected CheckBox checkbCRN16;
    protected CheckBox checkbCRN30;
    protected CheckBox checkbCRN60;
    protected TextField tfAnderPompType;
    protected CheckBox checkbDia12;
    protected CheckBox checkbDia16;
    protected CheckBox checkbDia28;
    protected CheckBox checkbDia38;
    protected CheckBox checkbDia48;
    protected CheckBox checkbHQQ;
    protected CheckBox checkbAUU;
    protected CheckBox checkbRUU;
    protected CheckBox checkbBUB;
    protected CheckBox checkbBAQ;
    protected CheckBox checkbBQQ;
    protected CheckBox checkbGQQ;
    protected CheckBox checkbEPDM;
    protected CheckBox checkbVITON;
    protected CheckBox checkbNeckWit;
    protected CheckBox checkbLagertje;
    protected CheckBox checkbNeckRingWaaier;
    protected CheckBox checkbNeckRingHouder;
    protected CheckBox checkbBodemLager;
    protected CheckBox checkbPompkapGietijzer;
    protected CheckBox checkbPompkapInox;
    protected CheckBox checkbVoetplaat;
    protected CheckBox checkbVoetstuk;
    protected CheckBox checkbORing;
    protected CheckBox checkbVeertjes;
    protected CheckBox checkbWaaier;
    protected CheckBox checkbAfgedraaideWaaier;
    protected CheckBox checkbTopKamer;
    protected CheckBox checkbKamer;
    protected CheckBox checkbKamerMetLager;
    protected CheckBox checkbOndersteKamer;
    protected CheckBox checkbTrekstang;
    protected CheckBox checkbTreklat;
    protected CheckBox checkbPompas;
    protected CheckBox checkbMantel;
    protected CheckBox checkbAfdekplaatjes;
    protected CheckBox checkbFlensDichtingen;
    protected CheckBox checkbFlens;
    protected Button bSave;

    public StockTellingDesign() {
        Design.read( this );
    }
}
